import doctor1 from "../../assets/logos/doctor1.jpg";
import doctor2 from "../../assets/logos/doctor2.jpg";
import doctor3 from "../../assets/logos/doctor3.jpg";

const topRatedDoctors = [
  {
    id: 1,
    name: "Dr. Sarah Johnson",
    image: doctor1,
    specialty: "Cardiologist",
    rating: 4.9,
    reviews: 1280,
    hospital: "Apollo Hospital",
    experience: "18 Years",
    fee: "₹1,500",
    availability: "Available Today",
    location: "Delhi",
  },

  {
    id: 2,
    name: "Dr. Michael Brown",
    image: doctor2,
    specialty: "Neurologist",
    rating: 4.8,
    reviews: 1150,
    hospital: "Fortis Hospital",
    experience: "16 Years",
    fee: "₹1,700",
    availability: "Available Today",
    location: "Mumbai",
  },

  {
    id: 3,
    name: "Dr. Emily Carter",
    image: doctor3,
    specialty: "Dermatologist",
    rating: 4.9,
    reviews: 980,
    hospital: "Medanta",
    experience: "14 Years",
    fee: "₹1,200",
    availability: "Available Tomorrow",
    location: "Gurugram",
  },

  {
    id: 4,
    name: "Dr. David Wilson",
    image: doctor1,
    specialty: "Orthopedic Surgeon",
    rating: 4.8,
    reviews: 1340,
    hospital: "Max Hospital",
    experience: "20 Years",
    fee: "₹2,000",
    availability: "Available Today",
    location: "Delhi",
  },

  {
    id: 5,
    name: "Dr. Olivia Thomas",
    image: doctor2,
    specialty: "Pediatrician",
    rating: 4.9,
    reviews: 1050,
    hospital: "Rainbow Hospital",
    experience: "15 Years",
    fee: "₹1,300",
    availability: "Available Today",
    location: "Hyderabad",
  },

  {
    id: 6,
    name: "Dr. James Anderson",
    image: doctor3,
    specialty: "ENT Specialist",
    rating: 4.7,
    reviews: 870,
    hospital: "BLK Hospital",
    experience: "17 Years",
    fee: "₹1,400",
    availability: "Available Tomorrow",
    location: "Delhi",
  },

  {
    id: 7,
    name: "Dr. Sophia Lee",
    image: doctor1,
    specialty: "Gynecologist",
    rating: 4.9,
    reviews: 1210,
    hospital: "Cloudnine Hospital",
    experience: "19 Years",
    fee: "₹1,800",
    availability: "Available Today",
    location: "Bengaluru",
  },

  {
    id: 8,
    name: "Dr. William Scott",
    image: doctor2,
    specialty: "Psychiatrist",
    rating: 4.8,
    reviews: 920,
    hospital: "AIIMS",
    experience: "13 Years",
    fee: "₹1,600",
    availability: "Available Today",
    location: "Delhi",
  },

  {
    id: 9,
    name: "Dr. Isabella Martin",
    image: doctor3,
    specialty: "Oncologist",
    rating: 4.9,
    reviews: 1450,
    hospital: "Tata Memorial",
    experience: "21 Years",
    fee: "₹2,500",
    availability: "Available Today",
    location: "Mumbai",
  },

  {
    id: 10,
    name: "Dr. Daniel Harris",
    image: doctor1,
    specialty: "Pulmonologist",
    rating: 4.8,
    reviews: 990,
    hospital: "Manipal Hospital",
    experience: "18 Years",
    fee: "₹1,900",
    availability: "Available Tomorrow",
    location: "Bengaluru",
  },
];

export default topRatedDoctors;
