import { useMemo, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, CreditCard, MapPin, ShieldCheck, Stethoscope } from "lucide-react";

const TIMES = ["09:00 AM", "09:30 AM", "10:30 AM", "11:00 AM", "11:30 AM", "02:00 PM", "03:00 PM", "03:30 PM"];
const STEPS = ["Date", "Time", "Your details", "Payment", "Confirmed"];
const getAmount = (fee) => Number(String(fee || "1500").replace(/[^0-9.]/g, "")) || 1500;
const formatDate = (date) => date.toLocaleDateString("en-IN", { weekday: "short", day: "numeric", month: "long", year: "numeric" });

function Input({ label, ...props }) {
  return <label className="block text-sm font-semibold text-slate-700">{label}<input {...props} required className="mt-1.5 w-full rounded-xl border border-teal-100 px-3 py-2.5 font-normal outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-100" /></label>;
}

export default function BookAppointment() {
  const { state } = useLocation();
  const navigate = useNavigate();
  const doctor = { name: "Your specialist", specialty: "Consultation", hospital: "MediCare partner clinic", fee: "₹1,500", ...(state?.doctor || {}) };
  const [step, setStep] = useState(0); const [date, setDate] = useState(); const [time, setTime] = useState(); const [mode, setMode] = useState("In-person"); const [method, setMethod] = useState("UPI"); const [reference] = useState("MC-DEMO-2026");
  const [form, setForm] = useState({ firstName: "", lastName: "", email: "", phone: "", reason: "" });
  const amount = getAmount(doctor.fee);
  const dates = useMemo(() => Array.from({ length: 10 }, (_, i) => { const next = new Date(); next.setDate(next.getDate() + i + 1); return next; }), []);
  const next = () => setStep(Math.min(step + 1, 4));
  const canContinue = [date, time, form.firstName && form.email && form.phone, true][step];
  const field = (name) => (e) => setForm({ ...form, [name]: e.target.value });
  return <main className="min-h-screen bg-gradient-to-br from-[#e8f8f6] via-[#f9fffe] to-[#d5f1ed] px-4 py-10 sm:px-6"><div className="mx-auto max-w-3xl">
    <button onClick={() => step ? setStep(step - 1) : navigate(-1)} className="mb-7 inline-flex items-center gap-2 text-sm font-semibold text-teal-800 hover:text-teal-950"><ChevronLeft size={18} />{step ? "Previous step" : "Back to doctors"}</button>
    <div className="mb-7 flex items-center justify-between gap-1">{STEPS.map((label, i) => <div key={label} className="flex flex-1 items-center last:flex-none"><div className="flex items-center gap-2 whitespace-nowrap text-xs font-semibold sm:text-sm"><span className={`grid h-7 w-7 place-items-center rounded-full border ${i < step ? "border-teal-600 bg-teal-600 text-white" : i === step ? "border-teal-600 bg-white text-teal-700" : "border-teal-100 bg-white text-slate-400"}`}>{i < step ? <Check size={15} /> : i + 1}</span><span className={i <= step ? "text-teal-800" : "hidden text-slate-400 sm:inline"}>{label}</span></div>{i < 4 && <div className={`mx-2 h-px flex-1 ${i < step ? "bg-teal-500" : "bg-teal-100"}`} />}</div>)}</div>
    <section className="mb-5 flex items-center gap-4 rounded-2xl border border-teal-100 bg-white/90 p-4 shadow-sm">{doctor.portraitPosition ? <div role="img" aria-label={doctor.name} className="h-14 w-14 rounded-xl bg-cover" style={{ backgroundImage: `url(${doctor.image})`, backgroundSize: "300% 200%", backgroundPosition: doctor.portraitPosition }} /> : doctor.image ? <img src={doctor.image} alt="" className="h-14 w-14 rounded-xl object-cover" /> : <div className="grid h-14 w-14 place-items-center rounded-xl bg-teal-100 text-teal-700"><Stethoscope /></div>}<div className="min-w-0 flex-1"><h1 className="truncate text-lg font-bold text-slate-900">{doctor.name}</h1><p className="truncate text-sm text-teal-700">{doctor.specialty || doctor.speciality || doctor.subspecialty || "Specialist"} · {doctor.hospital}</p></div><div className="text-right"><p className="text-xs text-slate-500">Consultation</p><p className="font-bold text-slate-900">₹{amount.toLocaleString("en-IN")}</p></div></section>
    <section className="rounded-3xl border border-teal-100 bg-white/95 p-5 shadow-xl shadow-teal-950/5 sm:p-7">
      {step === 0 && <><Header label="Step 1 of 4" title="Choose a visit date" copy="Select a convenient day for your consultation." /><div className="grid grid-cols-2 gap-3 sm:grid-cols-5">{dates.map((item) => <button key={item} onClick={() => setDate(item)} className={`rounded-2xl border p-4 text-left transition ${date?.toDateString() === item.toDateString() ? "border-teal-600 bg-teal-600 text-white shadow-md" : "border-teal-100 bg-teal-50/40 text-slate-700 hover:border-teal-300"}`}><CalendarDays size={18} className="mb-3" /><p className="text-xs opacity-80">{item.toLocaleDateString("en-IN", { weekday: "short" })}</p><p className="text-xl font-bold">{item.getDate()}</p><p className="text-xs">{item.toLocaleDateString("en-IN", { month: "short" })}</p></button>)}</div></>}
      {step === 1 && <><Header label={`Step 2 of 4 · ${formatDate(date)}`} title="Select a time" /><div className="mb-6 flex gap-3"><button onClick={() => setMode("In-person")} className={`rounded-xl px-4 py-2 text-sm font-semibold ${mode === "In-person" ? "bg-teal-600 text-white" : "bg-teal-50 text-teal-800"}`}><MapPin size={16} className="mr-1 inline" />In-person</button><button onClick={() => setMode("Video consultation")} className={`rounded-xl px-4 py-2 text-sm font-semibold ${mode !== "In-person" ? "bg-teal-600 text-white" : "bg-teal-50 text-teal-800"}`}>Video consultation</button></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{TIMES.map((item, i) => <button key={item} disabled={i === 1} onClick={() => setTime(item)} className={`rounded-xl border px-3 py-3 text-sm font-semibold transition disabled:cursor-not-allowed disabled:border-slate-100 disabled:bg-slate-50 disabled:text-slate-300 ${time === item ? "border-teal-600 bg-teal-600 text-white" : "border-teal-100 text-slate-700 hover:border-teal-400"}`}><Clock3 size={15} className="mr-1 inline" />{item}</button>)}</div></>}
      {step === 2 && <><Header label="Step 3 of 4" title="Your appointment details" copy="We’ll use these details for your confirmation." /><div className="grid gap-4 sm:grid-cols-2"><Input label="First name" value={form.firstName} onChange={field("firstName")} placeholder="Enter first name" /><Input label="Last name" value={form.lastName} onChange={field("lastName")} placeholder="Enter last name" /></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><Input label="Email address" type="email" value={form.email} onChange={field("email")} placeholder="you@example.com" /><Input label="Phone number" type="tel" value={form.phone} onChange={field("phone")} placeholder="+91 98765 43210" /></div><label className="mt-4 block text-sm font-semibold text-slate-700">Reason for visit<textarea value={form.reason} onChange={field("reason")} placeholder="Briefly describe what you would like help with (optional)" className="mt-1.5 min-h-24 w-full rounded-xl border border-teal-100 px-3 py-2.5 font-normal outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-100" /></label></>}
      {step === 3 && <><Header label="Step 4 of 4" title="Confirm your booking" copy="This is a demonstration payment — no money will be charged." /><div className="rounded-2xl bg-teal-50/70 p-5 text-sm"><div className="flex justify-between"><span>Consultation fee</span><b>₹{amount.toLocaleString("en-IN")}</b></div><div className="mt-3 flex justify-between border-t border-teal-100 pt-3 text-base font-bold"><span>Total</span><span>₹{amount.toLocaleString("en-IN")}</span></div></div><p className="mt-5 text-sm font-semibold text-slate-700">Payment method</p><div className="mt-2 grid grid-cols-3 gap-3">{["UPI", "Card", "Wallet"].map((item) => <button key={item} onClick={() => setMethod(item)} className={`rounded-xl border p-3 text-sm font-semibold ${method === item ? "border-teal-600 bg-teal-600 text-white" : "border-teal-100 text-slate-700"}`}>{item}</button>)}</div><div className="mt-5 flex items-center gap-2 text-xs text-slate-500"><ShieldCheck size={16} className="text-teal-600" />Secure demo checkout. Your payment details are not collected.</div></>}
      {step === 4 && <div className="py-8 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-emerald-100 text-emerald-600"><Check size={34} /></div><h2 className="mt-5 text-2xl font-bold text-slate-900">Appointment requested!</h2><p className="mx-auto mt-2 max-w-md text-sm text-slate-500">Your visit with {doctor.name} is confirmed for {formatDate(date)} at {time}. A confirmation has been prepared for {form.email}.</p><div className="mx-auto mt-6 max-w-sm rounded-2xl bg-teal-50 p-4 text-left text-sm"><p><b>Visit type:</b> {mode}</p><p className="mt-2"><b>Reference:</b> {reference}</p></div><button onClick={() => navigate("/")} className="mt-7 rounded-xl bg-teal-600 px-6 py-3 text-sm font-bold text-white hover:bg-teal-700">Return to home</button></div>}
      {step < 4 && <div className="mt-7 flex justify-end"><button disabled={!canContinue} onClick={next} className="inline-flex items-center gap-2 rounded-xl bg-teal-600 px-5 py-3 text-sm font-bold text-white transition hover:bg-teal-700 disabled:cursor-not-allowed disabled:bg-teal-200">{step === 3 ? <><CreditCard size={17} />Confirm demo payment</> : <>Continue <ChevronRight size={17} /></>}</button></div>}
    </section></div></main>;
}
function Header({ label, title, copy }) { return <div className="mb-6"><p className="text-sm font-semibold text-teal-700">{label}</p><h2 className="mt-1 text-2xl font-bold text-slate-900">{title}</h2>{copy && <p className="mt-1 text-sm text-slate-500">{copy}</p>}</div>; }
